
def content_heads():
    li = []
    
    one_list = [
        # added by habib
        # head, head_title
        ['career objective', 'career objective'],
        ['objective', 'career objective'],
        ['career aim', 'career objective'],
        ['career synopsis', 'career objective'],
        ['goals and objectives', 'career objective'],
        ['career objectives', 'career objective'],
        ['immediate goals', 'career objective'],
        ['my objective', 'career objective'],
        ['objectives', 'career objective'],
        ['summary', 'summary'],
        ['functional summary', 'summary'],
        ['career summary', 'summary'],
        ['personal summary', 'summary'],
        ['professional profile', 'summary'],
        ['career highlights', 'summary'],
        ['executive summary', 'summary'],
        ['synopsis', 'summary'],
        ['summary of qualification', 'summary'],
        ['highlights', 'summary'],
        ['summary of qualifications', 'summary'],
        ['summary / profile', 'summary'],
        ['profile', 'summary'],
        ['personal statement', 'summary'],
        ['professional experience summary', 'summary'],
        ['professional summary', 'summary'],
        ['profile overview', 'summary'],
        ['education', 'education'],
        ['educations', 'education'],
        ['educational qualifications', 'education'],
        ['educations (&) trainings', 'education'],
        ['academic qualification', 'education'],
        ['academic qualifications', 'education'],
        ['education and qualifications ', 'education'],
        ['academic attainment', 'education'],
        ['education level', 'education'],
        ['education background', 'education'],
        ['educational background', 'education'],
        ['education (&) qualifications', 'education'],
        ['education (&) training', 'education'],
        ['educations and qualifications', 'education'],
        ['academic background', 'education'],
        ['academics', 'education'],
        ['education and qualification ', 'education'],
        ['education (&) qualification', 'education'],
        ['professional and educational qualification', 'education'],
        ['education / qualifications', 'education'],
        ['education (&) professional qualifications', 'education'],
        ['academic data', 'education'],
        ['education (&) credentials', 'education'],
        ['academic profile', 'education'],
        ['qualifications and educations', 'education'],
        ['education history', 'education'],
        ['academic and professional qualifications', 'education'],
        ['academic credentials', 'education'],
        ['education and training', 'education'],
        ['academic/ professional qualification', 'education'],
        ['academic record', 'education'],
        ['education and professional registration', 'education'],
        ['my academic', 'education'],
        ['qualifications/educations', 'education'],
        ['education histories', 'education'],
        ['education and certifications', 'education'],
        ['formal education', 'education'],
        ['educational attainment', 'education'],
        ['education summary', 'education'],
        ['eduacation & professional qualification', 'education'],
        ['qualifications and educations', 'education'],
        ['education & professional certifications', 'education'],
        ['academic/professional qualifications', 'education'],
        ['work experience', 'work experience'],
        ['professional experience', 'work experience'],
        ['experiences', 'work experience'],
        ['experience', 'work experience'],
        ['work history', 'work experience'],
        ['functional expertise', 'work experience'],
        ['employment history', 'work experience'],
        ['work experiences', 'work experience'],
        ['employment profile', 'work experience'],
        ['working experience', 'work experience'],
        ['work experiences and job duties', 'work experience'],
        ['working experiences', 'work experience'],
        ['employment', 'work experience'],
        ['career history', 'work experience'],
        ['employment experience', 'work experience'],
        ['work (&) leadership experience', 'work experience'],
        ['professional experiences', 'work experience'],
        ['professional work experience', 'work experience'],
        ['corporate experience', 'work experience'],
        ['past employment', 'work experience'],
        ['employment record', 'work experience'],
        ['related experience', 'work experience'],
        ['work experience summary', 'work experience'],
        ['employment history -current', 'work experience'],
        ['history -previous', 'work experience'],
        ['practical experience', 'work experience'],
        ['carrier histories / experiences', 'work experience'],
        ['career overview', 'work experience'],
        ['summary of working experience', 'work experience'],
        ['career experience', 'work experience'],
        ['professional', 'work experience'],
        ['organisational experience', 'work experience'],
        ['career', 'work experience'],
        ['my work experience', 'work experience'],
        ['relevant work experience and skills', 'work experience'],
        ['employment history and working experience', 'work experience'],
        ['employment details', 'work experience'],
        ['professional work experiences and responsibilities', 'work experience'],
        ['employment histories and experiences', 'work experience'],
        ['employment background', 'work experience'],
        ['areas of expertise', 'work experience'],
        ['summary of experience', 'work experience'],
        ['knowledge of software usage', 'work experience'],
        ['employment highlights', 'work experience'],
        ['professional experience', 'work experience'],
        ['relevant experience', 'work experience'],
        ['skills', 'skills'],
        ['hard skills', 'skills'],
        ['soft skills', 'skills'],
        ['skills (&) abilities', 'skills'],
        ['competences', 'skills'],
        ['skills language and tools', 'skills'],
        ['specialization', 'skills'],
        ['programming skills', 'skills'],
        ['technical skill', 'skills'],
        ['technical skills', 'skills'],
        ['key skills', 'skills'],
        ['professional skills', 'skills'],
        ['language and pc skills', 'skills'],
        ['computer skill', 'skills'],
        ['computer knowledge', 'skills'],
        ['computer skills', 'skills'],
        ['it skills', 'skills'],
        ['professional qualifications', 'skills'],
        ['relevant skills', 'skills'],
        ['key skills and competencies', 'skills'],
        ['qualification summary and skills', 'skills'],
        ['core competencies', 'skills'],
        ['key skills and qualification', 'skills'],
        ['skills and capabilities', 'skills'],
        ['competencies (&) skills', 'skills'],
        ['business skills', 'skills'],
        ['technical competencies', 'skills'],
        ['software skills', 'skills'],
        ['it/is skills', 'skills'],
        ['personal skills', 'skills'],
        ['computer expertise', 'skills'],
        ['computer literacy', 'skills'],
        ['proficiency/expertise on tools', 'skills'],
        ['skill (&) competences', 'skills'],
        ['highlights of technical skills', 'skills'],
        ['computer proficiency', 'skills'],
        ['technical summary', 'skills'],
        ['professional qualification', 'skills'],
        ['computer and language skills', 'skills'],
        ['skill profile', 'skills'],
        ['computer / typing skills', 'skills'],
        ['skills and interests', 'skills'],
        ['skills/strength', 'skills'],
        ['knowledge and skills', 'skills'],
        ['computer literate', 'skills'],
        ['accounting software', 'skills'],
        ['other skills', 'skills'],
        ['a /c software', 'skills'],
        ['skills and strengths', 'skills'],
        ['computing', 'skills'],
        ['skills and attributes', 'skills'],
        ['summary of skills', 'skills'],
        ['area of expertise', 'skills'],
        ['software experience', 'skills'],
        ['language proficiency and skills', 'skills'],
        ['expertise and relevant skills', 'skills'],
        ['skillset', 'skills'],
        ['skills and interest', 'skills'],
        ['languages and computer skills', 'skills'],
        ['system skills', 'skills'],
        ['proficiencies', 'skills'],
        ['skills (&) strengths', 'skills'],
        ['technical proficiencies', 'skills'],
        ['computer applications', 'skills'],
        ['skills and computer literacy', 'skills'],
        ['skills/ additional info', 'skills'],
        ['specialities', 'skills'],
        ['skills/language/professional proficiency', 'skills'],
        ['my skills', 'skills'],
        ['language and computer skills', 'skills'],
        ['skills and key strengths', 'skills'],
        ['capabilities', 'skills'],
        ['computer and technical skills', 'skills'],
        ['demonstrated abilities', 'skills'],
        ['skills, abilities and language proficiency', 'skills'],
        ['knowledge of software usage', 'skills'],
        ['skills (&) interests', 'skills'],
        ['skill set', 'skills'],
        ['skills (&) characters', 'skills'],
        ['skills and abilities', 'skills'],
        ['skills and ability', 'skills'],
        ['qualification', 'skills'],
        ['competencies', 'skills'],
        ['additional skills', 'skills'],
        ['proficiencyexpertise on tools', 'skills'],
        ['research', 'research'],
        ['research works', 'research'],
        ['research/thesis', 'research'],
        ['thesis', 'research'],
        ['research experience', 'research'],
        ['peer-reviewed publications', 'research'],
        ['publications', 'research'],
        ['publication', 'research'],
        ['competitive programming', 'competitive programming'],
        ['competitive programming and achievements', 'competitive programming'],
        ['coding problem solving', 'competitive programming'],
        ['contests & participations', 'competitive programming'],
        ['projects', 'projects'],
        ['personal projects', 'projects'],
        ['project', 'projects'],
        ['professional projects', 'projects'],
        ['selective project', 'projects'],
        ['coding projects', 'projects'],
        ['experience/personal projects', 'projects'],
        ['thesis and projects', 'projects'],
        ['project accomplishments', 'projects'],
        ['organizations', 'organizations'],
        ['extracurricular', 'organizations'],
        ['affiliation', 'organizations'],
        ['extracurricular activities', 'organizations'],
        ['co-curricular experiences', 'organizations'],
        ['co-curricular activities', 'organizations'],
        ['societies (&) clubs', 'organizations'],
        ['membership', 'organizations'],
        ['professional body membership', 'organizations'],
        ['co-curricular achievements', 'organizations'],
        ['extracurricular activities (&) involvements', 'organizations'],
        ['extracurricular activities', 'organizations'],
        ['memberships', 'organizations'],
        ['curricular activities', 'organizations'],
        ['community involvement', 'organizations'],
        ['community service', 'organizations'],
        ['professional organizations', 'organizations'],
        ['professional membership', 'organizations'],
        ['extracurricular participation', 'organizations'],
        ['leadership experiences', 'organizations'],
        ['awards/achievements', 'organizations'],
        ['leadership positions', 'organizations'],
        ['co-curriculum involvement', 'organizations'],
        ['other activities', 'organizations'],
        ['extra curricular activities', 'organizations'],
        ['extracurricular activity', 'organizations'],
        ['personal information', 'personal information'],
        ['about me', 'personal information'],
        ['profile', 'personal information'],
        ['personal profile', 'personal information'],
        ['personal details', 'personal information'],
        ['personal particulars', 'personal information'],
        ['brief details', 'personal information'],
        ['personal data', 'personal information'],
        ['my personal information', 'personal information'],
        ['personal detail', 'personal information'],
        ['courses', 'courses'],
        ['course', 'courses'],
        ['courses/training', 'courses'],
        ['training', 'courses'],
        ['training (&) workshop', 'courses'],
        ['training summary', 'courses'],
        ['personal enrichment courses/ training', 'courses'],
        ['seminars and trainings', 'courses'],
        ['achievements', 'achievements'],
        ['achievements and other activities', 'achievements'],
        ['award (&) recognitions', 'achievements'],
        ['award (&) activities', 'achievements'],
        ['honours and awards', 'achievements'],
        ['achievements / award', 'achievements'],
        ['key achievements', 'achievements'],
        ['recognitions', 'achievements'],
        ['awards', 'achievements'],
        ['award/achievements', 'achievements'],
        ['awards and achievements', 'achievements'],
        ['educational awards (&) achievements', 'achievements'],
        ['academic awards', 'achievements'],
        ['contest participation', 'achievements'],
        ['scholarship and award / achievement', 'achievements'],
        ['educational awards', 'achievements'],
        ['academic achievements', 'achievements'],
        ['academic award', 'achievements'],
        ['personal achievement', 'achievements'],
        ['accomplishment and activities', 'achievements'],
        ['award', 'achievements'],
        ['leadership (&) achievements', 'achievements'],
        ['awards (&) other certificate of achievement', 'achievements'],
        ['awards received', 'achievements'],
        ['awards and appreciation', 'achievements'],
        ['awards and appreciations', 'achievements'],
        ['my achievement (&) awards', 'achievements'],
        ['achievements and involvements', 'achievements'],
        ['certificate and awards', 'achievements'],
        ['achievements and certificates', 'achievements'],
        ['awards & qualifications', 'achievements'],
        ['certifications', 'certifications'],
        ['certificates', 'certifications'],
        ['licenses (&) qualifications', 'certifications'],
        ['trainings (&) certifications', 'certifications'],
        ['coursework', 'certifications'],
        ['professional certification', 'certifications'],
        ['special training and accreditations', 'certifications'],
        ['public certification', 'certifications'],
        ['training and workshop summary', 'certifications'],
        ['courses & certificates', 'certifications'],
        ['course & certificates', 'certifications'],
        ['course & certificates', 'certifications'],
        ['course & certificate', 'certifications'],
        ['language', 'language'],
        ['languages', 'language'],
        ['language ability', 'language'],
        ['language proficiency', 'language'],
        ['language and skills', 'language'],
        ['language skills', 'language'],
        ['language abilities', 'language'],
        ['language proficiencies', 'language'],
        ['language expertise', 'language'],
        ['languages and dialects', 'language'],
        ['language spoken/written', 'language'],
        ['language and written', 'language'],
        ['contact', 'contact'],
        ['social reference', 'contact'],
        ['contact information', 'contact'],
        ['references', 'references'],
        ['reference', 'references'],
        ['recommendations', 'references'],
        ['referrals', 'references'],
        ['referee', 'references'],
        ['referrals/character referees', 'references'],
        ['others', 'others'],
        ['additional information', 'others'],
        ['professional summary', 'others'],
        ['other information', 'others'],
        ['interest', 'others'],
        ['hobbies', 'others'],
    ]

    about_li = [
        'p ersonal i nformation',
        'pe rsonal in formation',
        'per sonal inf ormation',
        'p ersonal information',
        'pe rsonal information',
        'per sonal information',
        'ersonal nformation',
        'rsonal formation',
        'sonal ormation',
        'ersonal information',
        'rsonal information',
        'sonal information',
        'personal information',
        'a bout m e',
        'ab out me ',
        'abo ut me ',
        'a bout me',
        'ab out me',
        'abo ut me',
        'bout e',
        'out ',
        'ut ',
        'bout me',
        'out me',
        'ut me',
        'about me',
        'p rofile',
        'pr ofile',
        'pro file',
        'rofile',
        'ofile',
        'file',
        'profile',
        'p ersonal p rofile',
        'pe rsonal pr ofile',
        'per sonal pro file',
        'p ersonal profile',
        'pe rsonal profile',
        'per sonal profile',
        'ersonal rofile',
        'rsonal ofile',
        'sonal file',
        'ersonal profile',
        'rsonal profile',
        'sonal profile',
        'personal profile',
        'p ersonal d etails',
        'pe rsonal de tails',
        'per sonal det ails',
        'p ersonal details',
        'pe rsonal details',
        'per sonal details',
        'ersonal etails',
        'rsonal tails',
        'sonal ails',
        'ersonal details',
        'rsonal details',
        'sonal details',
        'personal details',
        'p ersonal p articulars',
        'pe rsonal pa rticulars',
        'per sonal par ticulars',
        'p ersonal particulars',
        'pe rsonal particulars',
        'per sonal particulars',
        'ersonal articulars',
        'rsonal rticulars',
        'sonal ticulars',
        'ersonal particulars',
        'rsonal particulars',
        'sonal particulars',
        'personal particulars',
        'b rief d etails',
        'br ief de tails',
        'bri ef det ails',
        'b rief details',
        'br ief details',
        'bri ef details',
        'rief etails',
        'ief tails',
        'ef ails',
        'rief details',
        'ief details',
        'ef details',
        'brief details',
        'p ersonal d ata',
        'pe rsonal da ta',
        'per sonal dat a',
        'p ersonal data',
        'pe rsonal data',
        'per sonal data',
        'ersonal ata',
        'rsonal ta',
        'sonal a',
        'ersonal data',
        'rsonal data',
        'sonal data',
        'personal data',
        'm y p ersonal i nformation',
        'my  pe rsonal in formation',
        'my  per sonal inf ormation',
        'm y personal information',
        'my  personal information',
        'my  personal information',
        'y ersonal nformation',
        ' rsonal formation',
        ' sonal ormation',
        'y personal information',
        ' personal information',
        'personal information',
        'my personal information',
        'p ersonal d etail',
        'pe rsonal de tail',
        'per sonal det ail',
        'p ersonal detail',
        'pe rsonal detail',
        'per sonal detail',
        'ersonal etail',
        'rsonal tail',
        'sonal ail',
        'ersonal detail',
        'rsonal detail',
        'sonal detail',
        'personal detail',

    ]

    education_li = [
        'e ducation',
        'ed ucation',
        'edu cation',
        'ducation',
        'ucation',
        'cation',
        'education',
        'e ducational q ualifications',
        'ed ucational qu alifications',
        'edu cational qua lifications',
        'e ducational qualifications',
        'ed ucational qualifications',
        'edu cational qualifications',
        'ducational ualifications',
        'ucational alifications',
        'cational lifications',
        'ducational qualifications',
        'ucational qualifications',
        'cational qualifications',
        'educational qualifications',
        'e ducations (&) t rainings',
        'ed ucations (&) tr ainings',
        'edu cations (&) tra inings',
        'e ducations (&) trainings',
        'ed ucations (&) trainings',
        'edu cations (&) trainings',
        'ducations (&) rainings',
        'ucations (&) ainings',
        'cations (&) inings',
        'ducations (&) trainings',
        'ucations (&) trainings',
        'cations (&) trainings',
        'educations (&) trainings',
        'a cademic q ualification',
        'ac ademic qu alification',
        'aca demic qua lification',
        'a cademic qualification',
        'ac ademic qualification',
        'aca demic qualification',
        'cademic ualification',
        'ademic alification',
        'demic lification',
        'cademic qualification',
        'ademic qualification',
        'demic qualification',
        'academic qualification',
        'a cademic q ualifications',
        'ac ademic qu alifications',
        'aca demic qua lifications',
        'a cademic qualifications',
        'ac ademic qualifications',
        'aca demic qualifications',
        'cademic ualifications',
        'ademic alifications',
        'demic lifications',
        'cademic qualifications',
        'ademic qualifications',
        'demic qualifications',
        'academic qualifications',
        'e ducation a nd q ualifications',
        'ed ucation an d qu alifications',
        'edu cation and  qua lifications',
        'e ducation and qualifications ',
        'ed ucation and qualifications ',
        'edu cation and qualifications ',
        'ducation nd ualifications',
        'ucation d alifications',
        'cation  lifications',
        'ducation and qualifications ',
        'ucation and qualifications ',
        'cation and qualifications ',
        'education and qualifications ',
        'a cademic a ttainment',
        'ac ademic at tainment',
        'aca demic att ainment',
        'a cademic attainment',
        'ac ademic attainment',
        'aca demic attainment',
        'cademic ttainment',
        'ademic tainment',
        'demic ainment',
        'cademic attainment',
        'ademic attainment',
        'demic attainment',
        'academic attainment',
        'e ducation l evel',
        'ed ucation le vel',
        'edu cation lev el',
        'e ducation level',
        'ed ucation level',
        'edu cation level',
        'ducation evel',
        'ucation vel',
        'cation el',
        'ducation level',
        'ucation level',
        'cation level',
        'education level',
        'e ducation b ackground',
        'ed ucation ba ckground',
        'edu cation bac kground',
        'e ducation background',
        'ed ucation background',
        'edu cation background',
        'ducation ackground',
        'ucation ckground',
        'cation kground',
        'ducation background',
        'ucation background',
        'cation background',
        'education background',
        'e ducational b ackground',
        'ed ucational ba ckground',
        'edu cational bac kground',
        'e ducational background',
        'ed ucational background',
        'edu cational background',
        'ducational ackground',
        'ucational ckground',
        'cational kground',
        'ducational background',
        'ucational background',
        'cational background',
        'educational background',
        'e ducation (&) q ualifications',
        'ed ucation (&) qu alifications',
        'edu cation (&) qua lifications',
        'e ducation (&) qualifications',
        'ed ucation (&) qualifications',
        'edu cation (&) qualifications',
        'ducation (&) ualifications',
        'ucation (&) alifications',
        'cation (&) lifications',
        'ducation (&) qualifications',
        'ucation (&) qualifications',
        'cation (&) qualifications',
        'education (&) qualifications',
        'e ducation (&) t raining',
        'ed ucation (&) tr aining',
        'edu cation (&) tra ining',
        'e ducation (&) training',
        'ed ucation (&) training',
        'edu cation (&) training',
        'ducation (&) raining',
        'ucation (&) aining',
        'cation (&) ining',
        'ducation (&) training',
        'ucation (&) training',
        'cation (&) training',
        'education (&) training',
        'e ducations a nd q ualifications',
        'ed ucations an d qu alifications',
        'edu cations and  qua lifications',
        'e ducations and qualifications',
        'ed ucations and qualifications',
        'edu cations and qualifications',
        'ducations nd ualifications',
        'ucations d alifications',
        'cations  lifications',
        'ducations and qualifications',
        'ucations and qualifications',
        'cations and qualifications',
        'educations and qualifications',
        'a cademic b ackground',
        'ac ademic ba ckground',
        'aca demic bac kground',
        'a cademic background',
        'ac ademic background',
        'aca demic background',
        'cademic ackground',
        'ademic ckground',
        'demic kground',
        'cademic background',
        'ademic background',
        'demic background',
        'academic background',
        'a cademics',
        'ac ademics',
        'aca demics',
        'cademics',
        'ademics',
        'demics',
        'academics',
        'e ducation a nd q ualification',
        'ed ucation an d qu alification',
        'edu cation and  qua lification',
        'e ducation and qualification ',
        'ed ucation and qualification ',
        'edu cation and qualification ',
        'ducation nd ualification',
        'ucation d alification',
        'cation  lification',
        'ducation and qualification ',
        'ucation and qualification ',
        'cation and qualification ',
        'education and qualification ',
        'e ducation (&) q ualification',
        'ed ucation (&) qu alification',
        'edu cation (&) qua lification',
        'e ducation (&) qualification',
        'ed ucation (&) qualification',
        'edu cation (&) qualification',
        'ducation (&) ualification',
        'ucation (&) alification',
        'cation (&) lification',
        'ducation (&) qualification',
        'ucation (&) qualification',
        'cation (&) qualification',
        'education (&) qualification',
        'p rofessional a nd e ducational q ualification',
        'pr ofessional an d ed ucational qu alification',
        'pro fessional and  edu cational qua lification',
        'p rofessional and educational qualification',
        'pr ofessional and educational qualification',
        'pro fessional and educational qualification',
        'rofessional nd ducational ualification',
        'ofessional d ucational alification',
        'fessional  cational lification',
        'rofessional and educational qualification',
        'ofessional and educational qualification',
        'fessional and educational qualification',
        'professional and educational qualification',
        'e ducation /  q ualifications',
        'ed ucation /  qu alifications',
        'edu cation /  qua lifications',
        'e ducation / qualifications',
        'ed ucation / qualifications',
        'edu cation / qualifications',
        'ducation  ualifications',
        'ucation  alifications',
        'cation  lifications',
        'ducation / qualifications',
        'ucation / qualifications',
        'cation / qualifications',
        'education / qualifications',
        'e ducation (&) p rofessional q ualifications',
        'ed ucation (&) pr ofessional qu alifications',
        'edu cation (&) pro fessional qua lifications',
        'e ducation (&) professional qualifications',
        'ed ucation (&) professional qualifications',
        'edu cation (&) professional qualifications',
        'ducation (&) rofessional ualifications',
        'ucation (&) ofessional alifications',
        'cation (&) fessional lifications',
        'ducation (&) professional qualifications',
        'ucation (&) professional qualifications',
        'cation (&) professional qualifications',
        'education (&) professional qualifications',
        'a cademic d ata',
        'ac ademic da ta',
        'aca demic dat a',
        'a cademic data',
        'ac ademic data',
        'aca demic data',
        'cademic ata',
        'ademic ta',
        'demic a',
        'cademic data',
        'ademic data',
        'demic data',
        'academic data',
        'e ducation (&) c redentials',
        'ed ucation (&) cr edentials',
        'edu cation (&) cre dentials',
        'e ducation (&) credentials',
        'ed ucation (&) credentials',
        'edu cation (&) credentials',
        'ducation (&) redentials',
        'ucation (&) edentials',
        'cation (&) dentials',
        'ducation (&) credentials',
        'ucation (&) credentials',
        'cation (&) credentials',
        'education (&) credentials',
        'a cademic p rofile',
        'ac ademic pr ofile',
        'aca demic pro file',
        'a cademic profile',
        'ac ademic profile',
        'aca demic profile',
        'cademic rofile',
        'ademic ofile',
        'demic file',
        'cademic profile',
        'ademic profile',
        'demic profile',
        'academic profile',
        'q ualifications a nd e ducations',
        'qu alifications an d ed ucations',
        'qua lifications and  edu cations',
        'q ualifications and educations',
        'qu alifications and educations',
        'qua lifications and educations',
        'ualifications nd ducations',
        'alifications d ucations',
        'lifications  cations',
        'ualifications and educations',
        'alifications and educations',
        'lifications and educations',
        'qualifications and educations',
        'e ducation h istory',
        'ed ucation hi story',
        'edu cation his tory',
        'e ducation history',
        'ed ucation history',
        'edu cation history',
        'ducation istory',
        'ucation story',
        'cation tory',
        'ducation history',
        'ucation history',
        'cation history',
        'education history',
        'a cademic a nd p rofessional q ualifications',
        'ac ademic an d pr ofessional qu alifications',
        'aca demic and  pro fessional qua lifications',
        'a cademic and professional qualifications',
        'ac ademic and professional qualifications',
        'aca demic and professional qualifications',
        'cademic nd rofessional ualifications',
        'ademic d ofessional alifications',
        'demic  fessional lifications',
        'cademic and professional qualifications',
        'ademic and professional qualifications',
        'demic and professional qualifications',
        'academic and professional qualifications',
        'a cademic c redentials',
        'ac ademic cr edentials',
        'aca demic cre dentials',
        'a cademic credentials',
        'ac ademic credentials',
        'aca demic credentials',
        'cademic redentials',
        'ademic edentials',
        'demic dentials',
        'cademic credentials',
        'ademic credentials',
        'demic credentials',
        'academic credentials',
        'e ducation a nd t raining',
        'ed ucation an d tr aining',
        'edu cation and  tra ining',
        'e ducation and training',
        'ed ucation and training',
        'edu cation and training',
        'ducation nd raining',
        'ucation d aining',
        'cation  ining',
        'ducation and training',
        'ucation and training',
        'cation and training',
        'education and training',
        'a cademic/ p rofessional q ualification',
        'ac ademic/ pr ofessional qu alification',
        'aca demic/ pro fessional qua lification',
        'a cademic/ professional qualification',
        'ac ademic/ professional qualification',
        'aca demic/ professional qualification',
        'cademic/ rofessional ualification',
        'ademic/ ofessional alification',
        'demic/ fessional lification',
        'cademic/ professional qualification',
        'ademic/ professional qualification',
        'demic/ professional qualification',
        'academic/ professional qualification',
        'a cademic r ecord',
        'ac ademic re cord',
        'aca demic rec ord',
        'a cademic record',
        'ac ademic record',
        'aca demic record',
        'cademic ecord',
        'ademic cord',
        'demic ord',
        'cademic record',
        'ademic record',
        'demic record',
        'academic record',
        'e ducation a nd p rofessional r egistration',
        'ed ucation an d pr ofessional re gistration',
        'edu cation and  pro fessional reg istration',
        'e ducation and professional registration',
        'ed ucation and professional registration',
        'edu cation and professional registration',
        'ducation nd rofessional egistration',
        'ucation d ofessional gistration',
        'cation  fessional istration',
        'ducation and professional registration',
        'ucation and professional registration',
        'cation and professional registration',
        'education and professional registration',
        'm y a cademic',
        'my  ac ademic',
        'my  aca demic',
        'm y academic',
        'my  academic',
        'my  academic',
        'y cademic',
        ' ademic',
        ' demic',
        'y academic',
        ' academic',
        'academic',
        'my academic',
        'q ualifications/educations',
        'qu alifications/educations',
        'qua lifications/educations',
        'ualifications/educations',
        'alifications/educations',
        'lifications/educations',
        'qualifications/educations',
        'e ducation h istories',
        'ed ucation hi stories',
        'edu cation his tories',
        'e ducation histories',
        'ed ucation histories',
        'edu cation histories',
        'ducation istories',
        'ucation stories',
        'cation tories',
        'ducation histories',
        'ucation histories',
        'cation histories',
        'education histories',
        'e ducation a nd c ertifications',
        'ed ucation an d ce rtifications',
        'edu cation and  cer tifications',
        'e ducation and certifications',
        'ed ucation and certifications',
        'edu cation and certifications',
        'ducation nd ertifications',
        'ucation d rtifications',
        'cation  tifications',
        'ducation and certifications',
        'ucation and certifications',
        'cation and certifications',
        'education and certifications',
        'f ormal e ducation',
        'fo rmal ed ucation',
        'for mal edu cation',
        'f ormal education',
        'fo rmal education',
        'for mal education',
        'ormal ducation',
        'rmal ucation',
        'mal cation',
        'ormal education',
        'rmal education',
        'mal education',
        'formal education',
        'e ducational a ttainment',
        'ed ucational at tainment',
        'edu cational att ainment',
        'e ducational attainment',
        'ed ucational attainment',
        'edu cational attainment',
        'ducational ttainment',
        'ucational tainment',
        'cational ainment',
        'ducational attainment',
        'ucational attainment',
        'cational attainment',
        'educational attainment',
        'e ducation s ummary',
        'ed ucation su mmary',
        'edu cation sum mary',
        'e ducation summary',
        'ed ucation summary',
        'edu cation summary',
        'ducation ummary',
        'ucation mmary',
        'cation mary',
        'ducation summary',
        'ucation summary',
        'cation summary',
        'education summary',
    ]

    skill_li = [
        's kills',
        'sk ills',
        'ski lls',
        'kills',
        'ills',
        'lls',
        'skills',
        'h ard s kills',
        'ha rd sk ills',
        'har d ski lls',
        'h ard skills',
        'ha rd skills',
        'har d skills',
        'ard kills',
        'rd ills',
        'd lls',
        'ard skills',
        'rd skills',
        'd skills',
        'hard skills',
        's oft s kills',
        'so ft sk ills',
        'sof t ski lls',
        's oft skills',
        'so ft skills',
        'sof t skills',
        'oft kills',
        'ft ills',
        't lls',
        'oft skills',
        'ft skills',
        't skills',
        'soft skills',
        's kills (&) a bilities',
        'sk ills (&) ab ilities',
        'ski lls (&) abi lities',
        's kills (&) abilities',
        'sk ills (&) abilities',
        'ski lls (&) abilities',
        'kills (&) bilities',
        'ills (&) ilities',
        'lls (&) lities',
        'kills (&) abilities',
        'ills (&) abilities',
        'lls (&) abilities',
        'skills (&) abilities',
        'c ompetences',
        'co mpetences',
        'com petences',
        'ompetences',
        'mpetences',
        'petences',
        'competences',
        's kills l anguage a nd t ools',
        'sk ills la nguage an d to ols',
        'ski lls lan guage and  too ls',
        's kills language and tools',
        'sk ills language and tools',
        'ski lls language and tools',
        'kills anguage nd ools',
        'ills nguage d ols',
        'lls guage  ls',
        'kills language and tools',
        'ills language and tools',
        'lls language and tools',
        'skills language and tools',
        's pecialization',
        'sp ecialization',
        'spe cialization',
        'pecialization',
        'ecialization',
        'cialization',
        'specialization',
        'p rogramming s kills',
        'pr ogramming sk ills',
        'pro gramming ski lls',
        'p rogramming skills',
        'pr ogramming skills',
        'pro gramming skills',
        'rogramming kills',
        'ogramming ills',
        'gramming lls',
        'rogramming skills',
        'ogramming skills',
        'gramming skills',
        'programming skills',
        't echnical s kill',
        'te chnical sk ill',
        'tec hnical ski ll',
        't echnical skill',
        'te chnical skill',
        'tec hnical skill',
        'echnical kill',
        'chnical ill',
        'hnical ll',
        'echnical skill',
        'chnical skill',
        'hnical skill',
        'technical skill',
        't echnical s kills',
        'te chnical sk ills',
        'tec hnical ski lls',
        't echnical skills',
        'te chnical skills',
        'tec hnical skills',
        'echnical kills',
        'chnical ills',
        'hnical lls',
        'echnical skills',
        'chnical skills',
        'hnical skills',
        'technical skills',
        'k ey s kills',
        'ke y sk ills',
        'key  ski lls',
        'k ey skills',
        'ke y skills',
        'key  skills',
        'ey kills',
        'y ills',
        ' lls',
        'ey skills',
        'y skills',
        ' skills',
        'key skills',
        'p rofessional s kills',
        'pr ofessional sk ills',
        'pro fessional ski lls',
        'p rofessional skills',
        'pr ofessional skills',
        'pro fessional skills',
        'rofessional kills',
        'ofessional ills',
        'fessional lls',
        'rofessional skills',
        'ofessional skills',
        'fessional skills',
        'professional skills',
        'l anguage a nd p c s kills',
        'la nguage an d pc  sk ills',
        'lan guage and  pc  ski lls',
        'l anguage and pc skills',
        'la nguage and pc skills',
        'lan guage and pc skills',
        'anguage nd c kills',
        'nguage d  ills',
        'guage   lls',
        'anguage and pc skills',
        'nguage and pc skills',
        'guage and pc skills',
        'language and pc skills',
        'c omputer s kill',
        'co mputer sk ill',
        'com puter ski ll',
        'c omputer skill',
        'co mputer skill',
        'com puter skill',
        'omputer kill',
        'mputer ill',
        'puter ll',
        'omputer skill',
        'mputer skill',
        'puter skill',
        'computer skill',
        'c omputer k nowledge',
        'co mputer kn owledge',
        'com puter kno wledge',
        'c omputer knowledge',
        'co mputer knowledge',
        'com puter knowledge',
        'omputer nowledge',
        'mputer owledge',
        'puter wledge',
        'omputer knowledge',
        'mputer knowledge',
        'puter knowledge',
        'computer knowledge',
        'c omputer s kills',
        'co mputer sk ills',
        'com puter ski lls',
        'c omputer skills',
        'co mputer skills',
        'com puter skills',
        'omputer kills',
        'mputer ills',
        'puter lls',
        'omputer skills',
        'mputer skills',
        'puter skills',
        'computer skills',
        'i t s kills',
        'it  sk ills',
        'it  ski lls',
        'i t skills',
        'it  skills',
        'it  skills',
        't kills',
        ' ills',
        ' lls',
        't skills',
        ' skills',
        'skills',
        'it skills',
        'p rofessional q ualifications',
        'pr ofessional qu alifications',
        'pro fessional qua lifications',
        'p rofessional qualifications',
        'pr ofessional qualifications',
        'pro fessional qualifications',
        'rofessional ualifications',
        'ofessional alifications',
        'fessional lifications',
        'rofessional qualifications',
        'ofessional qualifications',
        'fessional qualifications',
        'professional qualifications',
        'r elevant s kills',
        're levant sk ills',
        'rel evant ski lls',
        'r elevant skills',
        're levant skills',
        'rel evant skills',
        'elevant kills',
        'levant ills',
        'evant lls',
        'elevant skills',
        'levant skills',
        'evant skills',
        'relevant skills',
        'k ey s kills a nd c ompetencies',
        'ke y sk ills an d co mpetencies',
        'key  ski lls and  com petencies',
        'k ey skills and competencies',
        'ke y skills and competencies',
        'key  skills and competencies',
        'ey kills nd ompetencies',
        'y ills d mpetencies',
        ' lls  petencies',
        'ey skills and competencies',
        'y skills and competencies',
        ' skills and competencies',
        'key skills and competencies',
        'q ualification s ummary a nd s kills',
        'qu alification su mmary an d sk ills',
        'qua lification sum mary and  ski lls',
        'q ualification summary and skills',
        'qu alification summary and skills',
        'qua lification summary and skills',
        'ualification ummary nd kills',
        'alification mmary d ills',
        'lification mary  lls',
        'ualification summary and skills',
        'alification summary and skills',
        'lification summary and skills',
        'qualification summary and skills',
        'c ore c ompetencies',
        'co re co mpetencies',
        'cor e com petencies',
        'c ore competencies',
        'co re competencies',
        'cor e competencies',
        'ore ompetencies',
        're mpetencies',
        'e petencies',
        'ore competencies',
        're competencies',
        'e competencies',
        'core competencies',
        'k ey s kills a nd q ualification',
        'ke y sk ills an d qu alification',
        'key  ski lls and  qua lification',
        'k ey skills and qualification',
        'ke y skills and qualification',
        'key  skills and qualification',
        'ey kills nd ualification',
        'y ills d alification',
        ' lls  lification',
        'ey skills and qualification',
        'y skills and qualification',
        ' skills and qualification',
        'key skills and qualification',
        's kills a nd c apabilities',
        'sk ills an d ca pabilities',
        'ski lls and  cap abilities',
        's kills and capabilities',
        'sk ills and capabilities',
        'ski lls and capabilities',
        'kills nd apabilities',
        'ills d pabilities',
        'lls  abilities',
        'kills and capabilities',
        'ills and capabilities',
        'lls and capabilities',
        'skills and capabilities',
        'c ompetencies (&) s kills',
        'co mpetencies (&) sk ills',
        'com petencies (&) ski lls',
        'c ompetencies (&) skills',
        'co mpetencies (&) skills',
        'com petencies (&) skills',
        'ompetencies (&) kills',
        'mpetencies (&) ills',
        'petencies (&) lls',
        'ompetencies (&) skills',
        'mpetencies (&) skills',
        'petencies (&) skills',
        'competencies (&) skills',
        'b usiness s kills',
        'bu siness sk ills',
        'bus iness ski lls',
        'b usiness skills',
        'bu siness skills',
        'bus iness skills',
        'usiness kills',
        'siness ills',
        'iness lls',
        'usiness skills',
        'siness skills',
        'iness skills',
        'business skills',
        't echnical c ompetencies',
        'te chnical co mpetencies',
        'tec hnical com petencies',
        't echnical competencies',
        'te chnical competencies',
        'tec hnical competencies',
        'echnical ompetencies',
        'chnical mpetencies',
        'hnical petencies',
        'echnical competencies',
        'chnical competencies',
        'hnical competencies',
        'technical competencies',
        's oftware s kills',
        'so ftware sk ills',
        'sof tware ski lls',
        's oftware skills',
        'so ftware skills',
        'sof tware skills',
        'oftware kills',
        'ftware ills',
        'tware lls',
        'oftware skills',
        'ftware skills',
        'tware skills',
        'software skills',
        'i t/is s kills',
        'it /is sk ills',
        'it/ is ski lls',
        'i t/is skills',
        'it /is skills',
        'it/ is skills',
        't/is kills',
        '/is ills',
        'is lls',
        't/is skills',
        '/is skills',
        'is skills',
        'it/is skills',
        'p ersonal s kills',
        'pe rsonal sk ills',
        'per sonal ski lls',
        'p ersonal skills',
        'pe rsonal skills',
        'per sonal skills',
        'ersonal kills',
        'rsonal ills',
        'sonal lls',
        'ersonal skills',
        'rsonal skills',
        'sonal skills',
        'personal skills',
        'c omputer e xpertise',
        'co mputer ex pertise',
        'com puter exp ertise',
        'c omputer expertise',
        'co mputer expertise',
        'com puter expertise',
        'omputer xpertise',
        'mputer pertise',
        'puter ertise',
        'omputer expertise',
        'mputer expertise',
        'puter expertise',
        'computer expertise',
        'c omputer l iteracy',
        'co mputer li teracy',
        'com puter lit eracy',
        'c omputer literacy',
        'co mputer literacy',
        'com puter literacy',
        'omputer iteracy',
        'mputer teracy',
        'puter eracy',
        'omputer literacy',
        'mputer literacy',
        'puter literacy',
        'computer literacy',
        'p roficiency/expertise o n t ools',
        'pr oficiency/expertise on  to ols',
        'pro ficiency/expertise on  too ls',
        'p roficiency/expertise on tools',
        'pr oficiency/expertise on tools',
        'pro ficiency/expertise on tools',
        'roficiency/expertise n ools',
        'oficiency/expertise  ols',
        'ficiency/expertise  ls',
        'roficiency/expertise on tools',
        'oficiency/expertise on tools',
        'ficiency/expertise on tools',
        'proficiency/expertise on tools',
        's kill (&) c ompetences',
        'sk ill (&) co mpetences',
        'ski ll (&) com petences',
        's kill (&) competences',
        'sk ill (&) competences',
        'ski ll (&) competences',
        'kill (&) ompetences',
        'ill (&) mpetences',
        'll (&) petences',
        'kill (&) competences',
        'ill (&) competences',
        'll (&) competences',
        'skill (&) competences',
        'h ighlights o f t echnical s kills',
        'hi ghlights of  te chnical sk ills',
        'hig hlights of  tec hnical ski lls',
        'h ighlights of technical skills',
        'hi ghlights of technical skills',
        'hig hlights of technical skills',
        'ighlights f echnical kills',
        'ghlights  chnical ills',
        'hlights  hnical lls',
        'ighlights of technical skills',
        'ghlights of technical skills',
        'hlights of technical skills',
        'highlights of technical skills',
        'c omputer p roficiency',
        'co mputer pr oficiency',
        'com puter pro ficiency',
        'c omputer proficiency',
        'co mputer proficiency',
        'com puter proficiency',
        'omputer roficiency',
        'mputer oficiency',
        'puter ficiency',
        'omputer proficiency',
        'mputer proficiency',
        'puter proficiency',
        'computer proficiency',
        't echnical s ummary',
        'te chnical su mmary',
        'tec hnical sum mary',
        't echnical summary',
        'te chnical summary',
        'tec hnical summary',
        'echnical ummary',
        'chnical mmary',
        'hnical mary',
        'echnical summary',
        'chnical summary',
        'hnical summary',
        'technical summary',
        'p rofessional q ualification',
        'pr ofessional qu alification',
        'pro fessional qua lification',
        'p rofessional qualification',
        'pr ofessional qualification',
        'pro fessional qualification',
        'rofessional ualification',
        'ofessional alification',
        'fessional lification',
        'rofessional qualification',
        'ofessional qualification',
        'fessional qualification',
        'professional qualification',
        'c omputer a nd l anguage s kills',
        'co mputer an d la nguage sk ills',
        'com puter and  lan guage ski lls',
        'c omputer and language skills',
        'co mputer and language skills',
        'com puter and language skills',
        'omputer nd anguage kills',
        'mputer d nguage ills',
        'puter  guage lls',
        'omputer and language skills',
        'mputer and language skills',
        'puter and language skills',
        'computer and language skills',
        's kill p rofile',
        'sk ill pr ofile',
        'ski ll pro file',
        's kill profile',
        'sk ill profile',
        'ski ll profile',
        'kill rofile',
        'ill ofile',
        'll file',
        'kill profile',
        'ill profile',
        'll profile',
        'skill profile',
        'c omputer /  t yping s kills',
        'co mputer /  ty ping sk ills',
        'com puter /  typ ing ski lls',
        'c omputer / typing skills',
        'co mputer / typing skills',
        'com puter / typing skills',
        'omputer  yping kills',
        'mputer  ping ills',
        'puter  ing lls',
        'omputer / typing skills',
        'mputer / typing skills',
        'puter / typing skills',
        'computer / typing skills',
        's kills a nd i nterests',
        'sk ills an d in terests',
        'ski lls and  int erests',
        's kills and interests',
        'sk ills and interests',
        'ski lls and interests',
        'kills nd nterests',
        'ills d terests',
        'lls  erests',
        'kills and interests',
        'ills and interests',
        'lls and interests',
        'skills and interests',
        's kills/strength',
        'sk ills/strength',
        'ski lls/strength',
        'kills/strength',
        'ills/strength',
        'lls/strength',
        'skills/strength',
        'k nowledge a nd s kills',
        'kn owledge an d sk ills',
        'kno wledge and  ski lls',
        'k nowledge and skills',
        'kn owledge and skills',
        'kno wledge and skills',
        'nowledge nd kills',
        'owledge d ills',
        'wledge  lls',
        'nowledge and skills',
        'owledge and skills',
        'wledge and skills',
        'knowledge and skills',
        'c omputer l iterate',
        'co mputer li terate',
        'com puter lit erate',
        'c omputer literate',
        'co mputer literate',
        'com puter literate',
        'omputer iterate',
        'mputer terate',
        'puter erate',
        'omputer literate',
        'mputer literate',
        'puter literate',
        'computer literate',
        'a ccounting s oftware',
        'ac counting so ftware',
        'acc ounting sof tware',
        'a ccounting software',
        'ac counting software',
        'acc ounting software',
        'ccounting oftware',
        'counting ftware',
        'ounting tware',
        'ccounting software',
        'counting software',
        'ounting software',
        'accounting software',
        'o ther s kills',
        'ot her sk ills',
        'oth er ski lls',
        'o ther skills',
        'ot her skills',
        'oth er skills',
        'ther kills',
        'her ills',
        'er lls',
        'ther skills',
        'her skills',
        'er skills',
        'other skills',
        'a  / c s oftware',
        'a  /c  so ftware',
        'a  /c  sof tware',
        'a  /c software',
        'a  /c software',
        'a / c software',
        ' c oftware',
        '  ftware',
        '  tware',
        ' /c software',
        '/c software',
        'c software',
        'a /c software',
        's kills a nd s trengths',
        'sk ills an d st rengths',
        'ski lls and  str engths',
        's kills and strengths',
        'sk ills and strengths',
        'ski lls and strengths',
        'kills nd trengths',
        'ills d rengths',
        'lls  engths',
        'kills and strengths',
        'ills and strengths',
        'lls and strengths',
        'skills and strengths',
        'c omputing',
        'co mputing',
        'com puting',
        'omputing',
        'mputing',
        'puting',
        'computing',
        's kills a nd a ttributes',
        'sk ills an d at tributes',
        'ski lls and  att ributes',
        's kills and attributes',
        'sk ills and attributes',
        'ski lls and attributes',
        'kills nd ttributes',
        'ills d tributes',
        'lls  ributes',
        'kills and attributes',
        'ills and attributes',
        'lls and attributes',
        'skills and attributes',
        's ummary o f s kills',
        'su mmary of  sk ills',
        'sum mary of  ski lls',
        's ummary of skills',
        'su mmary of skills',
        'sum mary of skills',
        'ummary f kills',
        'mmary  ills',
        'mary  lls',
        'ummary of skills',
        'mmary of skills',
        'mary of skills',
        'summary of skills',
        'a rea o f e xpertise',
        'ar ea of  ex pertise',
        'are a of  exp ertise',
        'a rea of expertise',
        'ar ea of expertise',
        'are a of expertise',
        'rea f xpertise',
        'ea  pertise',
        'a  ertise',
        'rea of expertise',
        'ea of expertise',
        'a of expertise',
        'area of expertise',
        's oftware e xperience',
        'so ftware ex perience',
        'sof tware exp erience',
        's oftware experience',
        'so ftware experience',
        'sof tware experience',
        'oftware xperience',
        'ftware perience',
        'tware erience',
        'oftware experience',
        'ftware experience',
        'tware experience',
        'software experience',
        'l anguage p roficiency a nd s kills',
        'la nguage pr oficiency an d sk ills',
        'lan guage pro ficiency and  ski lls',
        'l anguage proficiency and skills',
        'la nguage proficiency and skills',
        'lan guage proficiency and skills',
        'anguage roficiency nd kills',
        'nguage oficiency d ills',
        'guage ficiency  lls',
        'anguage proficiency and skills',
        'nguage proficiency and skills',
        'guage proficiency and skills',
        'language proficiency and skills',
        'e xpertise a nd r elevant s kills',
        'ex pertise an d re levant sk ills',
        'exp ertise and  rel evant ski lls',
        'e xpertise and relevant skills',
        'ex pertise and relevant skills',
        'exp ertise and relevant skills',
        'xpertise nd elevant kills',
        'pertise d levant ills',
        'ertise  evant lls',
        'xpertise and relevant skills',
        'pertise and relevant skills',
        'ertise and relevant skills',
        'expertise and relevant skills',
        's killset',
        'sk illset',
        'ski llset',
        'killset',
        'illset',
        'llset',
        'skillset',
        's kills a nd i nterest',
        'sk ills an d in terest',
        'ski lls and  int erest',
        's kills and interest',
        'sk ills and interest',
        'ski lls and interest',
        'kills nd nterest',
        'ills d terest',
        'lls  erest',
        'kills and interest',
        'ills and interest',
        'lls and interest',
        'skills and interest',
        'l anguages a nd c omputer s kills',
        'la nguages an d co mputer sk ills',
        'lan guages and  com puter ski lls',
        'l anguages and computer skills',
        'la nguages and computer skills',
        'lan guages and computer skills',
        'anguages nd omputer kills',
        'nguages d mputer ills',
        'guages  puter lls',
        'anguages and computer skills',
        'nguages and computer skills',
        'guages and computer skills',
        'languages and computer skills',
        's ystem s kills',
        'sy stem sk ills',
        'sys tem ski lls',
        's ystem skills',
        'sy stem skills',
        'sys tem skills',
        'ystem kills',
        'stem ills',
        'tem lls',
        'ystem skills',
        'stem skills',
        'tem skills',
        'system skills',
        'p roficiencies',
        'pr oficiencies',
        'pro ficiencies',
        'roficiencies',
        'oficiencies',
        'ficiencies',
        'proficiencies',
        's kills (&) s trengths',
        'sk ills (&) st rengths',
        'ski lls (&) str engths',
        's kills (&) strengths',
        'sk ills (&) strengths',
        'ski lls (&) strengths',
        'kills (&) trengths',
        'ills (&) rengths',
        'lls (&) engths',
        'kills (&) strengths',
        'ills (&) strengths',
        'lls (&) strengths',
        'skills (&) strengths',
        't echnical p roficiencies',
        'te chnical pr oficiencies',
        'tec hnical pro ficiencies',
        't echnical proficiencies',
        'te chnical proficiencies',
        'tec hnical proficiencies',
        'echnical roficiencies',
        'chnical oficiencies',
        'hnical ficiencies',
        'echnical proficiencies',
        'chnical proficiencies',
        'hnical proficiencies',
        'technical proficiencies',
        'c omputer a pplications',
        'co mputer ap plications',
        'com puter app lications',
        'c omputer applications',
        'co mputer applications',
        'com puter applications',
        'omputer pplications',
        'mputer plications',
        'puter lications',
        'omputer applications',
        'mputer applications',
        'puter applications',
        'computer applications',
        's kills a nd c omputer l iteracy',
        'sk ills an d co mputer li teracy',
        'ski lls and  com puter lit eracy',
        's kills and computer literacy',
        'sk ills and computer literacy',
        'ski lls and computer literacy',
        'kills nd omputer iteracy',
        'ills d mputer teracy',
        'lls  puter eracy',
        'kills and computer literacy',
        'ills and computer literacy',
        'lls and computer literacy',
        'skills and computer literacy',
        's kills/ a dditional i nfo',
        'sk ills/ ad ditional in fo',
        'ski lls/ add itional inf o',
        's kills/ additional info',
        'sk ills/ additional info',
        'ski lls/ additional info',
        'kills/ dditional nfo',
        'ills/ ditional fo',
        'lls/ itional o',
        'kills/ additional info',
        'ills/ additional info',
        'lls/ additional info',
        'skills/ additional info',
        's pecialities',
        'sp ecialities',
        'spe cialities',
        'pecialities',
        'ecialities',
        'cialities',
        'specialities',
        's kills/language/professional p roficiency',
        'sk ills/language/professional pr oficiency',
        'ski lls/language/professional pro ficiency',
        's kills/language/professional proficiency',
        'sk ills/language/professional proficiency',
        'ski lls/language/professional proficiency',
        'kills/language/professional roficiency',
        'ills/language/professional oficiency',
        'lls/language/professional ficiency',
        'kills/language/professional proficiency',
        'ills/language/professional proficiency',
        'lls/language/professional proficiency',
        'skills/language/professional proficiency',
        'm y s kills',
        'my  sk ills',
        'my  ski lls',
        'm y skills',
        'my  skills',
        'my  skills',
        'y kills',
        ' ills',
        ' lls',
        'y skills',
        ' skills',
        'skills',
        'my skills',
        'l anguage a nd c omputer s kills',
        'la nguage an d co mputer sk ills',
        'lan guage and  com puter ski lls',
        'l anguage and computer skills',
        'la nguage and computer skills',
        'lan guage and computer skills',
        'anguage nd omputer kills',
        'nguage d mputer ills',
        'guage  puter lls',
        'anguage and computer skills',
        'nguage and computer skills',
        'guage and computer skills',
        'language and computer skills',
        's kills a nd k ey s trengths',
        'sk ills an d ke y st rengths',
        'ski lls and  key  str engths',
        's kills and key strengths',
        'sk ills and key strengths',
        'ski lls and key strengths',
        'kills nd ey trengths',
        'ills d y rengths',
        'lls   engths',
        'kills and key strengths',
        'ills and key strengths',
        'lls and key strengths',
        'skills and key strengths',
        'c apabilities',
        'ca pabilities',
        'cap abilities',
        'apabilities',
        'pabilities',
        'abilities',
        'capabilities',
        'c omputer a nd t echnical s kills',
        'co mputer an d te chnical sk ills',
        'com puter and  tec hnical ski lls',
        'c omputer and technical skills',
        'co mputer and technical skills',
        'com puter and technical skills',
        'omputer nd echnical kills',
        'mputer d chnical ills',
        'puter  hnical lls',
        'omputer and technical skills',
        'mputer and technical skills',
        'puter and technical skills',
        'computer and technical skills',
        'd emonstrated a bilities',
        'de monstrated ab ilities',
        'dem onstrated abi lities',
        'd emonstrated abilities',
        'de monstrated abilities',
        'dem onstrated abilities',
        'emonstrated bilities',
        'monstrated ilities',
        'onstrated lities',
        'emonstrated abilities',
        'monstrated abilities',
        'onstrated abilities',
        'demonstrated abilities',
        's kills, a bilities a nd l anguage p roficiency',
        'sk ills, ab ilities an d la nguage pr oficiency',
        'ski lls, abi lities and  lan guage pro ficiency',
        's kills, abilities and language proficiency',
        'sk ills, abilities and language proficiency',
        'ski lls, abilities and language proficiency',
        'kills, bilities nd anguage roficiency',
        'ills, ilities d nguage oficiency',
        'lls, lities  guage ficiency',
        'kills, abilities and language proficiency',
        'ills, abilities and language proficiency',
        'lls, abilities and language proficiency',
        'skills, abilities and language proficiency',
        'k nowledge o f s oftware u sage',
        'kn owledge of  so ftware us age',
        'kno wledge of  sof tware usa ge',
        'k nowledge of software usage',
        'kn owledge of software usage',
        'kno wledge of software usage',
        'nowledge f oftware sage',
        'owledge  ftware age',
        'wledge  tware ge',
        'nowledge of software usage',
        'owledge of software usage',
        'wledge of software usage',
        'knowledge of software usage',
        's kills (&) i nterests',
        'sk ills (&) in terests',
        'ski lls (&) int erests',
        's kills (&) interests',
        'sk ills (&) interests',
        'ski lls (&) interests',
        'kills (&) nterests',
        'ills (&) terests',
        'lls (&) erests',
        'kills (&) interests',
        'ills (&) interests',
        'lls (&) interests',
        'skills (&) interests',
        's kill s et',
        'sk ill se t',
        'ski ll set ',
        's kill set',
        'sk ill set',
        'ski ll set',
        'kill et',
        'ill t',
        'll ',
        'kill set',
        'ill set',
        'll set',
        'skill set',
        's kills (&) c haracters',
        'sk ills (&) ch aracters',
        'ski lls (&) cha racters',
        's kills (&) characters',
        'sk ills (&) characters',
        'ski lls (&) characters',
        'kills (&) haracters',
        'ills (&) aracters',
        'lls (&) racters',
        'kills (&) characters',
        'ills (&) characters',
        'lls (&) characters',
        'skills (&) characters',

    ]

    experience_li = [
        'w ork e xperience',
        'wo rk ex perience',
        'wor k exp erience',
        'w ork experience',
        'wo rk experience',
        'wor k experience',
        'ork xperience',
        'rk perience',
        'k erience',
        'ork experience',
        'rk experience',
        'k experience',
        'work experience',
        'p rofessional e xperience',
        'pr ofessional ex perience',
        'pro fessional exp erience',
        'p rofessional experience',
        'pr ofessional experience',
        'pro fessional experience',
        'rofessional xperience',
        'ofessional perience',
        'fessional erience',
        'rofessional experience',
        'ofessional experience',
        'fessional experience',
        'professional experience',
        'e xperiences',
        'ex periences',
        'exp eriences',
        'xperiences',
        'periences',
        'eriences',
        'experiences',
        'e xperience',
        'ex perience',
        'exp erience',
        'xperience',
        'perience',
        'erience',
        'experience',
        'w ork h istory',
        'wo rk hi story',
        'wor k his tory',
        'w ork history',
        'wo rk history',
        'wor k history',
        'ork istory',
        'rk story',
        'k tory',
        'ork history',
        'rk history',
        'k history',
        'work history',
        'f unctional e xpertise',
        'fu nctional ex pertise',
        'fun ctional exp ertise',
        'f unctional expertise',
        'fu nctional expertise',
        'fun ctional expertise',
        'unctional xpertise',
        'nctional pertise',
        'ctional ertise',
        'unctional expertise',
        'nctional expertise',
        'ctional expertise',
        'functional expertise',
        'e mployment h istory',
        'em ployment hi story',
        'emp loyment his tory',
        'e mployment history',
        'em ployment history',
        'emp loyment history',
        'mployment istory',
        'ployment story',
        'loyment tory',
        'mployment history',
        'ployment history',
        'loyment history',
        'employment history',
        'w ork e xperiences',
        'wo rk ex periences',
        'wor k exp eriences',
        'w ork experiences',
        'wo rk experiences',
        'wor k experiences',
        'ork xperiences',
        'rk periences',
        'k eriences',
        'ork experiences',
        'rk experiences',
        'k experiences',
        'work experiences',
        'e mployment p rofile',
        'em ployment pr ofile',
        'emp loyment pro file',
        'e mployment profile',
        'em ployment profile',
        'emp loyment profile',
        'mployment rofile',
        'ployment ofile',
        'loyment file',
        'mployment profile',
        'ployment profile',
        'loyment profile',
        'employment profile',
        'w orking e xperience',
        'wo rking ex perience',
        'wor king exp erience',
        'w orking experience',
        'wo rking experience',
        'wor king experience',
        'orking xperience',
        'rking perience',
        'king erience',
        'orking experience',
        'rking experience',
        'king experience',
        'working experience',
        'w ork e xperiences a nd j ob d uties',
        'wo rk ex periences an d jo b du ties',
        'wor k exp eriences and  job  dut ies',
        'w ork experiences and job duties',
        'wo rk experiences and job duties',
        'wor k experiences and job duties',
        'ork xperiences nd ob uties',
        'rk periences d b ties',
        'k eriences   ies',
        'ork experiences and job duties',
        'rk experiences and job duties',
        'k experiences and job duties',
        'work experiences and job duties',
        'w orking e xperiences',
        'wo rking ex periences',
        'wor king exp eriences',
        'w orking experiences',
        'wo rking experiences',
        'wor king experiences',
        'orking xperiences',
        'rking periences',
        'king eriences',
        'orking experiences',
        'rking experiences',
        'king experiences',
        'working experiences',
        'e mployment',
        'em ployment',
        'emp loyment',
        'mployment',
        'ployment',
        'loyment',
        'employment',
        'c areer h istory',
        'ca reer hi story',
        'car eer his tory',
        'c areer history',
        'ca reer history',
        'car eer history',
        'areer istory',
        'reer story',
        'eer tory',
        'areer history',
        'reer history',
        'eer history',
        'career history',
        'e mployment e xperience',
        'em ployment ex perience',
        'emp loyment exp erience',
        'e mployment experience',
        'em ployment experience',
        'emp loyment experience',
        'mployment xperience',
        'ployment perience',
        'loyment erience',
        'mployment experience',
        'ployment experience',
        'loyment experience',
        'employment experience',
        'w ork (&) l eadership e xperience',
        'wo rk (&) le adership ex perience',
        'wor k (&) lea dership exp erience',
        'w ork (&) leadership experience',
        'wo rk (&) leadership experience',
        'wor k (&) leadership experience',
        'ork (&) eadership xperience',
        'rk (&) adership perience',
        'k (&) dership erience',
        'ork (&) leadership experience',
        'rk (&) leadership experience',
        'k (&) leadership experience',
        'work (&) leadership experience',
        'p rofessional e xperiences',
        'pr ofessional ex periences',
        'pro fessional exp eriences',
        'p rofessional experiences',
        'pr ofessional experiences',
        'pro fessional experiences',
        'rofessional xperiences',
        'ofessional periences',
        'fessional eriences',
        'rofessional experiences',
        'ofessional experiences',
        'fessional experiences',
        'professional experiences',
        'p rofessional w ork e xperience',
        'pr ofessional wo rk ex perience',
        'pro fessional wor k exp erience',
        'p rofessional work experience',
        'pr ofessional work experience',
        'pro fessional work experience',
        'rofessional ork xperience',
        'ofessional rk perience',
        'fessional k erience',
        'rofessional work experience',
        'ofessional work experience',
        'fessional work experience',
        'professional work experience',
        'c orporate e xperience',
        'co rporate ex perience',
        'cor porate exp erience',
        'c orporate experience',
        'co rporate experience',
        'cor porate experience',
        'orporate xperience',
        'rporate perience',
        'porate erience',
        'orporate experience',
        'rporate experience',
        'porate experience',
        'corporate experience',
        'p ast e mployment',
        'pa st em ployment',
        'pas t emp loyment',
        'p ast employment',
        'pa st employment',
        'pas t employment',
        'ast mployment',
        'st ployment',
        't loyment',
        'ast employment',
        'st employment',
        't employment',
        'past employment',
        'e mployment r ecord',
        'em ployment re cord',
        'emp loyment rec ord',
        'e mployment record',
        'em ployment record',
        'emp loyment record',
        'mployment ecord',
        'ployment cord',
        'loyment ord',
        'mployment record',
        'ployment record',
        'loyment record',
        'employment record',
        'r elated e xperience',
        're lated ex perience',
        'rel ated exp erience',
        'r elated experience',
        're lated experience',
        'rel ated experience',
        'elated xperience',
        'lated perience',
        'ated erience',
        'elated experience',
        'lated experience',
        'ated experience',
        'related experience',
        'w ork e xperience s ummary',
        'wo rk ex perience su mmary',
        'wor k exp erience sum mary',
        'w ork experience summary',
        'wo rk experience summary',
        'wor k experience summary',
        'ork xperience ummary',
        'rk perience mmary',
        'k erience mary',
        'ork experience summary',
        'rk experience summary',
        'k experience summary',
        'work experience summary',
        'e mployment h istory - current',
        'em ployment hi story -c urrent',
        'emp loyment his tory -cu rrent',
        'e mployment history -current',
        'em ployment history -current',
        'emp loyment history -current',
        'mployment istory current',
        'ployment story urrent',
        'loyment tory rrent',
        'mployment history -current',
        'ployment history -current',
        'loyment history -current',
        'employment history -current',
        'h istory - previous',
        'hi story -p revious',
        'his tory -pr evious',
        'h istory -previous',
        'hi story -previous',
        'his tory -previous',
        'istory previous',
        'story revious',
        'tory evious',
        'istory -previous',
        'story -previous',
        'tory -previous',
        'history -previous',
        'p ractical e xperience',
        'pr actical ex perience',
        'pra ctical exp erience',
        'p ractical experience',
        'pr actical experience',
        'pra ctical experience',
        'ractical xperience',
        'actical perience',
        'ctical erience',
        'ractical experience',
        'actical experience',
        'ctical experience',
        'practical experience',
        'c arrier h istories /  e xperiences',
        'ca rrier hi stories /  ex periences',
        'car rier his tories /  exp eriences',
        'c arrier histories / experiences',
        'ca rrier histories / experiences',
        'car rier histories / experiences',
        'arrier istories  xperiences',
        'rrier stories  periences',
        'rier tories  eriences',
        'arrier histories / experiences',
        'rrier histories / experiences',
        'rier histories / experiences',
        'carrier histories / experiences',
        'c areer o verview',
        'ca reer ov erview',
        'car eer ove rview',
        'c areer overview',
        'ca reer overview',
        'car eer overview',
        'areer verview',
        'reer erview',
        'eer rview',
        'areer overview',
        'reer overview',
        'eer overview',
        'career overview',
        's ummary o f w orking e xperience',
        'su mmary of  wo rking ex perience',
        'sum mary of  wor king exp erience',
        's ummary of working experience',
        'su mmary of working experience',
        'sum mary of working experience',
        'ummary f orking xperience',
        'mmary  rking perience',
        'mary  king erience',
        'ummary of working experience',
        'mmary of working experience',
        'mary of working experience',
        'summary of working experience',
        'c areer e xperience',
        'ca reer ex perience',
        'car eer exp erience',
        'c areer experience',
        'ca reer experience',
        'car eer experience',
        'areer xperience',
        'reer perience',
        'eer erience',
        'areer experience',
        'reer experience',
        'eer experience',
        'career experience',
        'p rofessional',
        'pr ofessional',
        'pro fessional',
        'rofessional',
        'ofessional',
        'fessional',
        'professional',
        'o rganisational e xperience',
        'or ganisational ex perience',
        'org anisational exp erience',
        'o rganisational experience',
        'or ganisational experience',
        'org anisational experience',
        'rganisational xperience',
        'ganisational perience',
        'anisational erience',
        'rganisational experience',
        'ganisational experience',
        'anisational experience',
        'organisational experience',
        'c areer',
        'ca reer',
        'car eer',
        'areer',
        'reer',
        'eer',
        'career',
        'm y w ork e xperience',
        'my  wo rk ex perience',
        'my  wor k exp erience',
        'm y work experience',
        'my  work experience',
        'my  work experience',
        'y ork xperience',
        ' rk perience',
        ' k erience',
        'y work experience',
        ' work experience',
        'work experience',
        'my work experience',
        'r elevant w ork e xperience a nd s kills',
        're levant wo rk ex perience an d sk ills',
        'rel evant wor k exp erience and  ski lls',
        'r elevant work experience and skills',
        're levant work experience and skills',
        'rel evant work experience and skills',
        'elevant ork xperience nd kills',
        'levant rk perience d ills',
        'evant k erience  lls',
        'elevant work experience and skills',
        'levant work experience and skills',
        'evant work experience and skills',
        'relevant work experience and skills',
        'e mployment h istory a nd w orking e xperience',
        'em ployment hi story an d wo rking ex perience',
        'emp loyment his tory and  wor king exp erience',
        'e mployment history and working experience',
        'em ployment history and working experience',
        'emp loyment history and working experience',
        'mployment istory nd orking xperience',
        'ployment story d rking perience',
        'loyment tory  king erience',
        'mployment history and working experience',
        'ployment history and working experience',
        'loyment history and working experience',
        'employment history and working experience',
        'e mployment d etails',
        'em ployment de tails',
        'emp loyment det ails',
        'e mployment details',
        'em ployment details',
        'emp loyment details',
        'mployment etails',
        'ployment tails',
        'loyment ails',
        'mployment details',
        'ployment details',
        'loyment details',
        'employment details',
        'p rofessional w ork e xperiences a nd r esponsibilities',
        'pr ofessional wo rk ex periences an d re sponsibilities',
        'pro fessional wor k exp eriences and  res ponsibilities',
        'p rofessional work experiences and responsibilities',
        'pr ofessional work experiences and responsibilities',
        'pro fessional work experiences and responsibilities',
        'rofessional ork xperiences nd esponsibilities',
        'ofessional rk periences d sponsibilities',
        'fessional k eriences  ponsibilities',
        'rofessional work experiences and responsibilities',
        'ofessional work experiences and responsibilities',
        'fessional work experiences and responsibilities',
        'professional work experiences and responsibilities',
        'e mployment h istories a nd e xperiences',
        'em ployment hi stories an d ex periences',
        'emp loyment his tories and  exp eriences',
        'e mployment histories and experiences',
        'em ployment histories and experiences',
        'emp loyment histories and experiences',
        'mployment istories nd xperiences',
        'ployment stories d periences',
        'loyment tories  eriences',
        'mployment histories and experiences',
        'ployment histories and experiences',
        'loyment histories and experiences',
        'employment histories and experiences',
        'e mployment b ackground',
        'em ployment ba ckground',
        'emp loyment bac kground',
        'e mployment background',
        'em ployment background',
        'emp loyment background',
        'mployment ackground',
        'ployment ckground',
        'loyment kground',
        'mployment background',
        'ployment background',
        'loyment background',
        'employment background',
        'a reas o f e xpertise',
        'ar eas of  ex pertise',
        'are as of  exp ertise',
        'a reas of expertise',
        'ar eas of expertise',
        'are as of expertise',
        'reas f xpertise',
        'eas  pertise',
        'as  ertise',
        'reas of expertise',
        'eas of expertise',
        'as of expertise',
        'areas of expertise',
        's ummary o f e xperience',
        'su mmary of  ex perience',
        'sum mary of  exp erience',
        's ummary of experience',
        'su mmary of experience',
        'sum mary of experience',
        'ummary f xperience',
        'mmary  perience',
        'mary  erience',
        'ummary of experience',
        'mmary of experience',
        'mary of experience',
        'summary of experience',
        'k nowledge o f s oftware u sage',
        'kn owledge of  so ftware us age',
        'kno wledge of  sof tware usa ge',
        'k nowledge of software usage',
        'kn owledge of software usage',
        'kno wledge of software usage',
        'nowledge f oftware sage',
        'owledge  ftware age',
        'wledge  tware ge',
        'nowledge of software usage',
        'owledge of software usage',
        'wledge of software usage',
        'knowledge of software usage',

    ]
    
    project_li = [
        'p rojects',
        'pr ojects',
        'pro jects',
        'rojects',
        'ojects',
        'jects',
        'projects',
        'p ersonal p rojects',
        'pe rsonal pr ojects',
        'per sonal pro jects',
        'p ersonal projects',
        'pe rsonal projects',
        'per sonal projects',
        'ersonal rojects',
        'rsonal ojects',
        'sonal jects',
        'ersonal projects',
        'rsonal projects',
        'sonal projects',
        'personal projects',
        'p roject',
        'pr oject',
        'pro ject',
        'roject',
        'oject',
        'ject',
        'project',
        'p rofessional p rojects',
        'pr ofessional pr ojects',
        'pro fessional pro jects',
        'p rofessional projects',
        'pr ofessional projects',
        'pro fessional projects',
        'rofessional rojects',
        'ofessional ojects',
        'fessional jects',
        'rofessional projects',
        'ofessional projects',
        'fessional projects',
        'professional projects',
        's elective p roject',
        'se lective pr oject',
        'sel ective pro ject',
        's elective project',
        'se lective project',
        'sel ective project',
        'elective roject',
        'lective oject',
        'ective ject',
        'elective project',
        'lective project',
        'ective project',
        'selective project',
        'c oding p rojects',
        'co ding pr ojects',
        'cod ing pro jects',
        'c oding projects',
        'co ding projects',
        'cod ing projects',
        'oding rojects',
        'ding ojects',
        'ing jects',
        'oding projects',
        'ding projects',
        'ing projects',
        'coding projects',
        'e xperience/personal p rojects',
        'ex perience/personal pr ojects',
        'exp erience/personal pro jects',
        'e xperience/personal projects',
        'ex perience/personal projects',
        'exp erience/personal projects',
        'xperience/personal rojects',
        'perience/personal ojects',
        'erience/personal jects',
        'xperience/personal projects',
        'perience/personal projects',
        'erience/personal projects',
        'experience/personal projects',
        't hesis a nd p rojects',
        'th esis an d pr ojects',
        'the sis and  pro jects',
        't hesis and projects',
        'th esis and projects',
        'the sis and projects',
        'hesis nd rojects',
        'esis d ojects',
        'sis  jects',
        'hesis and projects',
        'esis and projects',
        'sis and projects',
        'thesis and projects',
        'p roject a ccomplishments',
        'pr oject ac complishments',
        'pro ject acc omplishments',
        'p roject accomplishments',
        'pr oject accomplishments',
        'pro ject accomplishments',
        'roject ccomplishments',
        'oject complishments',
        'ject omplishments',
        'roject accomplishments',
        'oject accomplishments',
        'ject accomplishments',
        'project accomplishments',

    ]
    reference_li = [
        'r eferences',
        're ferences',
        'ref erences',
        'eferences',
        'ferences',
        'erences',
        'references',
        'r eference',
        're ference',
        'ref erence',
        'eference',
        'ference',
        'erence',
        'reference',
        'r ecommendations',
        're commendations',
        'rec ommendations',
        'ecommendations',
        'commendations',
        'ommendations',
        'recommendations',
        'r eferrals',
        're ferrals',
        'ref errals',
        'eferrals',
        'ferrals',
        'errals',
        'referrals',
        'r eferee',
        're feree',
        'ref eree',
        'eferee',
        'feree',
        'eree',
        'referee',
        'r eferrals/character r eferees',
        're ferrals/character re ferees',
        'ref errals/character ref erees',
        'r eferrals/character referees',
        're ferrals/character referees',
        'ref errals/character referees',
        'eferrals/character eferees',
        'ferrals/character ferees',
        'errals/character erees',
        'eferrals/character referees',
        'ferrals/character referees',
        'errals/character referees',
        'referrals/character referees',

    ]

    return li, one_list, about_li, education_li, skill_li, experience_li, project_li, reference_li

if __name__ == '__main__':
    heads = content_heads()
    print(heads[1])
    only_heads = [h[0] for h in heads[1]]
    print(only_heads)